imports:
- path: ../network/network-full-template.jinja
  name: network-full-template.jinja
- path: ../network/network-template.jinja
  name: network-template.jinja
- path: ../network/subnetwork-template.jinja
  name: subnetwork-template.jinja
- path: ../network/network-firewall-template.jinja
  name: network-firewall-template.jinja
- path: ../network/address-template.jinja
  name: address-template.jinja
- path: zookeeper-template.jinja
- path: zookeeper-firewall-template.jinja
- path: zookeeper-full-template.jinja
- path: zookeeper-startup.sh

resources:
- name: zookeeper-full
  type: zookeeper-full-template.jinja
